[package]
name = "alicesaidhi/jorp"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
pebble = "alicesaidhi/pebble@0.1.0-rc.3"
vide = "aloroid/vide-with-types@0.2.7"
jecs = "ukendio/jecs@0.3.0-rc.0"
t = "corecii/greentea@0.4.7"